services:
  plexcontroller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plexcontroller
    hostname: plexcontroller    
    environment:
      - TELEGRAM_BOT_TOKEN=tu_token_plex_aqui
      - TELEGRAM_API_URL=http://telegram-bot-api:8089
      - PLEX_SERVER_1_URL=http://192.168.1.100:32400
      - PLEX_SERVER_1_TOKEN=tu_token_plex_aqui
      - PLEX_SERVER_2_URL=http://192.168.1.101:32500
      - PLEX_SERVER_2_TOKEN=tu_token_plex_aqui
      - GLANCES_SERVER_1_URL=http://192.168.1.100:61208
      - GLANCES_SERVER_2_URL=http://192.168.1.101:61208
    restart: unless-stopped
    networks:
      - plexcontroller
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  plexcontroller:
    driver: bridge

volumes:
  data:

